//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public events()
        {
            this.participations = new HashSet<participations>();
        }
    
        public System.Guid id { get; set; }
        public bool archived { get; set; }
        public System.Guid author { get; set; }
        public string name { get; set; }
        public System.Guid category { get; set; }
        public System.DateTime date { get; set; }
        public string description { get; set; }
        public byte[] preview { get; set; }
        public Nullable<int> cost { get; set; }
    
        public virtual categories categories { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<participations> participations { get; set; }
    }
}
