//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventsContext : DbContext
    {
        public EventsContext()
            : base("name=EventsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accessLevels> accessLevels { get; set; }
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<events> events { get; set; }
        public virtual DbSet<participations> participations { get; set; }
        public virtual DbSet<reviews> reviews { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
