//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviews
    {
        public System.Guid id { get; set; }
        public System.Guid participationID { get; set; }
        public byte rating { get; set; }
        public string reviewText { get; set; }
    
        public virtual participations participations { get; set; }
    }
}
